### ISSUE TITLE
Diagnostics do not account for iOS backup file paths

### ISSUE THREAD

**Issue by ReagentX** [ReagentX/imessage-exporter#118]
Current diagnostic calculations do not take into account the file path manipulation we must perform in order to find attachments in an iOS backup:

https://github.com/ReagentX/imessage-exporter/blob/30e9c17e63584d17a157ccaaf606dc3f458c4b0c/imessage-database/src/tables/attachment.rs#L107-L116

This works for MacOS because correct filepaths are stored in the database directly, whereas in iOS there is an intermediary parsing step required to build the real path:

https://github.com/ReagentX/imessage-exporter/blob/30e9c17e63584d17a157ccaaf606dc3f458c4b0c/imessage-database/src/tables/attachment.rs#L216

**Comment by 1314520wbup** [comment]
How can I use Apple ID to send imessage information infinitely, how can I not be blocked, how can I not lock my ID, and how can I send imessage information without restrictions? If you have any technical skills, please contact my tg wsnbb9944
