### ISSUE TITLE
Add contact name to filename

### ISSUE THREAD

**Issue by tddostu** [ReagentX/imessage-exporter#126]
Hi, currently when I export messages the text/html files outputted are named something like +61411112222.html (or local equivalent). Is it possible to include the contact name in the file? This would allow for easier sorting and searching by name _or_ number.

**Comment by ReagentX** [comment]
See #62

**Comment by ReagentX** [comment]
Native support for contact detail resolution was merged via #631 and was released in [Desert Globemallow](https://github.com/ReagentX/imessage-exporter/releases/tag/3.2.0).
