### ISSUE TITLE
Panic - Filename too long

### ISSUE THREAD

**Issue by ssardegna** [ReagentX/imessage-exporter#14]
The program generates the following panic when exporting messages:

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 63, kind: InvalidFilename, message: "File name too long" }', imessage-exporter/src/exporters/txt.rs:250:14
```

This appears to happen when a group chat name is concatenated to too long of a string.

**Comment by ReagentX** [comment]
This can be addressed here:

https://github.com/ReagentX/imessage-exporter/blob/76eaed6563882905d8563a03c6d59629d4f18aa9/imessage-exporter/src/app/runtime.rs#L126-L130
