### ISSUE TITLE
Parsing older .iChat files?

### ISSUE THREAD

**Issue by simX** [ReagentX/imessage-exporter#142]
When exporting my current Messages database, it seems like the database only holds messages back to about May 2020 for me.  Before then, I seem to have messages stored either in ~/Library/Containers/com.apple.iChat/Data/Library/Messages/Archive (from 2013-2020), or in ~/Documents/iChats (2010-2012), and these are nested folders with chats saved individually in .iChat files.  But it seems like these are no longer parsable by Messages in the latest version of macOS (Ventura 13.4.1).

It doesn't seem like iMessage-exporter supports the older .iChat files, is that correct?  Not sure if it really makes sense to support them, but was wondering if that would be something simple to support.

I did notice that you said in issue #69 that you have older chat.db's from 2011, but it's weird that my chat.db doesn't go back nearly that far.  Maybe it took me longer to update to a version of macOS that migrated to the chat.db format, but I'm not exactly sure which version of macOS that would be.  I had been on macOS Mojave for a while, but as far as I know that still uses the newer chat.db format.

**Comment by ReagentX** [comment]
This tool targets the current release of iMessage on MacOS only.
