### ISSUE TITLE
imessage-exporter not showing up in full disk access control

### ISSUE THREAD

**Issue by Tintouin** [ReagentX/imessage-exporter#144]
I installed it with brew, and the command does not show up in full disk access control, so i added it manually, but it still doesn't work. Diagnostic works fine, but im unable to set the chat.db path.

**Comment by ReagentX** [comment]
What command are you running and what is the output?

**Comment by Tintouin** [comment]
imessage-exporter -p /Users/[USERNAME]/Library/Messages/chat.db

**Comment by Tintouin** [comment]
Ok now somehow it works, but really strangely, it is not appearing in my preferences 
<img width="832" alt="Capture d’écran 2023-07-05 à 22 09 11" src="https://github.com/ReagentX/imessage-exporter/assets/82973239/490fc927-71fc-4b6b-8847-40177034c8bf">
<img width="830" alt="Capture d’écran 2023-07-05 à 22 09 00" src="https://github.com/ReagentX/imessage-exporter/assets/82973239/62cbbabe-0dc5-421a-9918-2d506340406f">

**Comment by Tintouin** [comment]
to make it work im not really sure of what I done, I just uninstalled an re-installed, but that is not the first time I've done that.
Im sorry if I bothered you it's really strange... you helped in some way I guess... feel free to close the issue if you don't have any further questions.
