### ISSUE TITLE
Does not support old (itunes?) iOS backup directory structure

### ISSUE THREAD

**Issue by mcneb10** [ReagentX/imessage-exporter#146]
I don't know if my iOS backup is too old or too new, but it fails to extract the file with
`Unable to launch: Database not found at <backup folder>/3d/3d0d7e5fb2ce288813306e4d4636395e047a3d28`
In my backup, there are no folders with hash? prefixes. All of the files in the backup are in one folder.
I made this backup with iTunes on windows if that helps.
Can support be added for this directory structure?

**Comment by ReagentX** [comment]
Is the backup encrypted? If so, that is not supported.

**Comment by mcneb10** [comment]
The backup is not encrypted

**Comment by mcneb10** [comment]
All of the files the program tries to access (such as 3d0d7e5fb2ce288813306e4d4636395e047a3d28) are readable, they are all just stored in the same directory for some reason. I had a look at 3d0d7e5fb2ce288813306e4d4636395e047a3d28 in a mysql db viewer and I can read all the messages.

**Comment by mcneb10** [comment]
When I moved the message database file to it's folder with the 2 letter prefix, the program worked fine except without the attachments because I didn't make the folders for them

**Comment by ReagentX** [comment]
I think older backups use a different directory structure as you mentioned. This tool only targets the current versions:

https://github.com/ReagentX/imessage-exporter/blob/develop/docs/features.md#targeted-versions
