### ISSUE TITLE
Unable to retrieve all messages & attachments?

### ISSUE THREAD

**Issue by tomwarham** [ReagentX/imessage-exporter#170]
Appologies if this isn't too technical. 

I can't seem to get message history & attachment export to go back much longer than a couple of months in the export. 

I've tried setting a date in the commend line such as 2018-01-01 as the start date with no luck. 

Its exporting roughly 800mb of attachments wit the -c efficient flag doing no attachment conversion, but the iPhone is stating there are 12gb worth of messages & files on the device. 

I've ensured local backup from the device is set to "back up all the data on your iPhone to this mac" but this also doesn't seem to help. It is stating the device backup is located in `~/Library/Application Support/MobileSync/Backup/<backup id>` which doesn't look to contain any .db files for messages.

Whereas the chat.db file which imessage-exporter seems to use is `~/Library/Messages/chat.db` which even more confusingly the attachments folder here is 1.65gb so something doesn't seem to be adding up. 

Any help is apreciated, and TL:DR; it feels like a case of pebdak on my part not being able to get the full chat.db file off my phone somehow. 

TIA

**Comment by ReagentX** [comment]
> Whereas the chat.db file which imessage-exporter seems to use is `~/Library/Messages/chat.db`

The software defaults to using the local macOS iMessage database. If you want to read from your iOS backup, specify the path to it in the command with `-p`. Per the docs:

```
-p, --db-path <path/to/source>
        Specify a custom path for the iMessage database location
        For macOS, specify a path to a `chat.db` file
        For iOS, specify a path to the root of an unencrypted backup directory
        If omitted, the default directory is ~/Library/Messages/chat.db
``` 

For example, a command like the following would export your iOS backup:

```zsh
imessage-exporter -f html -p ~/Library/Application Support/MobileSync/Backup/<backup id> -a iOS
```

For more info, see some example commands [here](https://github.com/ReagentX/imessage-exporter/blob/develop/imessage-exporter/README.md#examples).
