### ISSUE TITLE
Better error if specified database path exists but is not an iMessage database

### ISSUE THREAD

**Issue by ReagentX** [ReagentX/imessage-exporter#177]
Given a command like

```
% imessage-exporter -f html -p ~/Documents
```

The error raised looks like:

```
Unable to launch: Unable to read from chat database: disk I/O error
Ensure full disk access is enabled for your terminal emulator in System Settings > Security and Privacy > Full Disk Access
```

The error should instead tell the user that the path does not point to a database file and should not warn the user about disk access permissions.

**Comment by af1** [comment]
Thanks for this, helped me figure out you need to include the chats.db in the pathname not just the directory

**Comment by rlxmp** [comment]
Looking forward to this fix too!
