### ISSUE TITLE
Arguments are apparently not parsed correctly with respect to the doc

### ISSUE THREAD

**Issue by lucbouge** [ReagentX/imessage-exporter#189]
Dear colleagues,

Thank you for this long-awaited utiity.

I downloaded it to my Somona 14.0 Intel Mac today from Homebrew

> % brew info imessage-exporter
> ==> imessage-exporter: stable 1.6.0 (bottled)
> Command-line tool to export and inspect local iMessage database
> https://github.com/ReagentX/imessage-exporter
> /usr/local/Cellar/imessage-exporter/1.6.0 (7 files, 3.2MB) *
>   Poured from bottle using the formulae.brew.sh API on 2023-11-05 at 17:43:29
> From: https://github.com/Homebrew/homebrew-core/blob/HEAD/Formula/i/imessage-exporter.rb
> License: GPL-3.0-only
> ==> Dependencies
> Build: rust ✘
> ==> Analytics
> install: 107 (30 days), 384 (90 days), 829 (365 days)
> install-on-request: 107 (30 days), 384 (90 days), 829 (365 days)
> build-error: 0 (30 days)

It works fine with the `diagnostics` argument:

> % imessage-exporter --diagnostics                                                                       
> Building cache...
> [1/4] Caching chats...
> [2/4] Caching chatrooms...
> [3/4] Caching participants...
> [4/4] Caching reactions...
> Cache built!
> 
> iMessage Database Diagnostics
> 
> Message diagnostic data:
>     Messages not associated with a chat: 80
> Attachment diagnostic data:
>     Total attachments: 5
>     Total attachment data: 454.07 KB
> Duplicated contacts: 1
> Done!

However, there looks to be a problem in the parsing of the regular arguments. Or might I missed something? 

> %  imessage-exporter  --format txt  

works fine, but not

> % imessage-exporter  --format txt  --no-lazy                          
> Invalid options!
> Option no-lazy is enabled, which requires `--format`

**Comment by ReagentX** [comment]
This is working as intended, but the error message is incorrect:

https://github.com/ReagentX/imessage-exporter/blob/6eb170e69ede7e8b61409225441cfc161f81c972/imessage-exporter/src/app/options.rs#L98-L101

You cannot use `no-lazy` with a `txt` export because text files can't embed data the way `html` can. I need to re-write the error message to reflect this.

**Comment by lucbouge** [comment]
Thanks for your quick reaction. Again, thanks for your awesome utility software. And congrats for the use of Rust! 🙂
