### ISSUE TITLE
HTML in messages not correctly escaped

### ISSUE THREAD

**Issue by christopher-wong** [ReagentX/imessage-exporter#217]
<img width="551" alt="Screenshot 2023-11-28 at 5 34 23 PM" src="https://github.com/ReagentX/imessage-exporter/assets/10580086/e10bafc2-b39a-495e-a301-afa9a6095c42">

**Comment by ReagentX** [comment]
Related: #32

**Comment by ReagentX** [comment]
<img width="492" alt="image" src="https://github.com/ReagentX/imessage-exporter/assets/1920666/3def6dec-4bd7-4956-8c74-23296b0c506c">
