### ISSUE TITLE
Edited message thread originators not properly rendered

### ISSUE THREAD

**Issue by podviaznikov** [ReagentX/imessage-exporter#220]
I think if edited message and table element are present in the generated html -> one closing div will be missing and that would produce invalid html.

**Comment by ReagentX** [comment]
The only place we add table elements is for edited messages:

https://github.com/ReagentX/imessage-exporter/blob/569762ce521f4b3547ab281587c9a46236013afa/imessage-exporter/src/exporters/html.rs#L715-L741

Did the messages you are viewing contain HTML themselves? If so this will be fixed in #219.

**Comment by ReagentX** [comment]
The generated HTML of an edited message looks like this:

```html
<div class="message">
    <div class="sent iMessage">
        <p><span class="timestamp">Nov 18, 2022 6:17:54 PM</span>
            <span class="sender">Me</span>
        </p>
        <hr>
        <div class="message_part">
            <div class="edited">
                <table>
                    <tbody>
                        <tr>
                            <td><span class="timestamp"></span></td>
                            <td>First message </td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <td><span class="timestamp">Edited 6 seconds later</span></td>
                            <td>Edit 1</td>
                        </tr>
                    </tbody>
                    <tbody>
                        <tr>
                            <td><span class="timestamp">Edited 5 seconds later</span></td>
                            <td>Edit 2</td>
                        </tr>
                    </tbody>
                    <tfoot>
                        <tr>
                            <td><span class="timestamp">Edited 9 seconds later</span></td>
                            <td>Edited message</td>
                        </tr>
                    </tfoot>
                </table>
            </div>
        </div>
        <div class="reactions">
            <hr>
            <p>Reactions:</p>
            <div class="reaction"><span class="reaction"><b>Liked</b> by Me</span></div>

        </div>
    </div>
</div>
```

I dont see an unclosed `div` here.

**Comment by podviaznikov** [comment]
<img width="1458" alt="Screenshot 2023-11-29 at 2 58 05 PM" src="https://github.com/ReagentX/imessage-exporter/assets/429706/9521975d-ee50-4796-8c08-bbd9b840bb14">

Hard to reproduce because basically now generated html is broken.

But here on the screenshot I have 3 separated messages and last two are nested inside 3rd to last in HTML because 3rd to last is missing one closing div.

**Comment by ReagentX** [comment]
What do the bubbles look like in the messages app? It looks like there was a thread off of a message that was deleted.

**Comment by podviaznikov** [comment]
yes, it was deleted. only message "Hi2" 2nd to last is visible.

**Comment by ReagentX** [comment]
Just to be clear—these were messages that were deleted from the conversation, not messages that were unsent from the conversation, correct?

**Comment by podviaznikov** [comment]
yes, deleted

**Comment by ReagentX** [comment]
Rendering the thread is definitely broken for edited messages. This is the culprit: 

https://github.com/ReagentX/imessage-exporter/blob/b9b4ed6c127f74eff0d5c661d753779a4024f5a5/imessage-exporter/src/exporters/html.rs#L301

To replicate the bug:

1. Send a message
2. Edit that message
3. Send a second message
4. Reply to 1. with a third message
5. Edit the third message

**Comment by ReagentX** [comment]
<img width="513" alt="image" src="https://github.com/ReagentX/imessage-exporter/assets/1920666/a3ad14b2-5a45-4555-9b4f-dfd97e9fa5e7">

**Comment by podviaznikov** [comment]
verified. thank you!
