### ISSUE TITLE
Integrate Contacts framework

### ISSUE THREAD

**Issue by lhunath** [ReagentX/imessage-exporter#233]
Using the [Contacts](https://developer.apple.com/documentation/contacts) framework, we could:
1. Associate names with contacts
2. Further de-duplicate messages

Changing the export filenames as well as contact addresses in the file to contact names would greatly improve the usefulness of the export.

We also notice that iMessage can merge or separate out chats based on what information is in your contact card, so presumably we should mirror that behaviour.

**Comment by ReagentX** [comment]
See #62

**Comment by ReagentX** [comment]
Native support for contact detail resolution was merged via #631 and was released in [Desert Globemallow](https://github.com/ReagentX/imessage-exporter/releases/tag/3.2.0).

**Comment by lhunath** [comment]
> We also notice that iMessage can merge or separate out chats based on what information is in your contact card, so presumably we should mirror that behaviour.

Is this a useful behavior to continue to track?

**Comment by ReagentX** [comment]
That was resolved by changes introduced to resolve #628, among other deduplication logic `imessage-exporter` already performs.
