### ISSUE TITLE
json export 

### ISSUE THREAD

**Issue by suchcodemuchwow** [ReagentX/imessage-exporter#236]
Hello 👋 

I just discovered this repo used it as executable and loved it. _Thanks for the great effort!!!_

I wish I could contribute it with the feature I'm asking but as a developer who do not have knowledge about Rust, it's a big breaker.

It would greatly enhance the usability and flexibility of the imessage-exporter crate if JSON support were implemented. JSON is widely used and supported across various programming languages and platforms, making it much easier to parse and manipulate message data programmatically. 

**Benefits:**
Simplifies message parsing and manipulation.
Enhances interoperability with other systems and applications.
Enables seamless integration with JSON-based workflows and tools.

**Requested Feature:**
Integrate JSON support into the imessage-exporter crate to provide an alternative output format alongside existing formats like txt and html.

**Additional Information:**
Given the widespread adoption and versatility of JSON, its inclusion would undoubtedly be a valuable addition to the functionality of the imessage-exporter crate. This enhancement would streamline development workflows and open up new possibilities for utilizing iMessage data.

**Comment by ReagentX** [comment]
#232
