### ISSUE TITLE
Bug: Group chat message appearing in personal chat export

### ISSUE THREAD

**Issue by klabast** [ReagentX/imessage-exporter#243]
Hi,

I have exported all my messages. In the txt file of a chat with 1 person `A`, suddenly appears a message from person `B`.
I checked and the message is indeed from a group chat from `me`, `A` and `B`
 Strangely, the message does not appear in the txt file of person `B`.
Also I can't find this particular group chat as an export.

I have yet to check if i can reproduce it, but there are group exports as far as I can see.

Since, I cannot (don't want to :) ) share my personal chats, how are we going to approach this?

**Comment by ReagentX** [comment]
It sounds like there is some kind of misalignment in the `chat.db`'s `chat_handle_join` table or the respective `chat_id` for that message row in the `message` table. How does this message appear in Messages.app?

**Comment by klabast** [comment]
I just realized I can simple open the chat.db, I will have a look inside tomorrow. In the Messages.app it's three chats. One with `A`, one with `B` and one with both.

**Comment by ReagentX** [comment]
In which chat does the message in question present? What `chat_id` does it map to compared to messages that belong to all 3?

**Comment by klabast** [comment]
@ReagentX sorry, I've been on the road a bit. I have yet to familiarise myself with the structure of chat.db. Do you have a query handy that I can use to search for a message containing a text? I hope to get to investigate on the weekend.

**Comment by ReagentX** [comment]
It isn't really possible to query the text field anymore because the relevant data is actually stored in a binary blob column, sadly.

**Comment by ReagentX** [comment]
Closing because this is not possible to debug without more information. If you find a way to get some details necessary for debugging or recreating this, I will reopen it.
