### ISSUE TITLE
"zsh: command not found: $" error

### ISSUE THREAD

**Issue by comfortablemilk4454** [ReagentX/imessage-exporter#253]
hi. sorry if this is a dumb question but im trying to use the program and im getting the `zsh: command not found: $` error:
<img width="682" alt="image" src="https://github.com/ReagentX/imessage-exporter/assets/43555540/8e270e89-5ae6-4555-9dab-271813b57830">

any fixes? pls explain to me like im 5 cuz idk anything about coding. thanks so much!

**Comment by ReagentX** [comment]
See #244

**Comment by comfortablemilk4454** [comment]
im now getting this error 
<img width="682" alt="image" src="https://github.com/ReagentX/imessage-exporter/assets/43555540/2f38840b-65b4-4cef-a62d-c0b4a6642490">

**Comment by ReagentX** [comment]
The answer is explained in #244; please omit the `PS1` character.

**Comment by ComfortableMilk4454** [comment]
oh i see. now i have this problem lmfao, but when i go to full disk access i dont see the toggle for it.

**Comment by comfortablemilk4454** [comment]
tysm, it worked!
