### ISSUE TITLE
Contact name database

### ISSUE THREAD

**Issue by salexgit** [ReagentX/imessage-exporter#278]
Hi

When messages are exported, each conversation thread is assigned the corresponding filename based on the phone number or the email address. However, it is often the case a phone number and email point to the same person, i.e. messages should be exported to the same file. 

It is possible to add a simple feature, e.g. contacts.txt database, where a user can specify the relationship between a person and a phone number and/or email address.

**Comment by ReagentX** [comment]
Native support for contact detail resolution was merged via #631 and was released in [Desert Globemallow](https://github.com/ReagentX/imessage-exporter/releases/tag/3.2.0).
