### ISSUE TITLE
Unable to write

### ISSUE THREAD

**Issue by data-source** [ReagentX/imessage-exporter#288]
Getting repeated issues, tried all sorts of installs cargo/brew/binary same behaviour

`Unable to write to "/Users/<user>/Desktop/export/+123456789.html": Os { code: 1, kind: PermissionDenied, message: "Operation not permitted" }`

**Comment by ReagentX** [comment]
Your user doesn't have write permissions for the folder. This isn't a problem with `imessage-exporter`.

See:

- https://support.apple.com/guide/security/controlling-app-access-to-files-secddd1d86a6/web
- https://support.apple.com/guide/mac-help/change-permissions-for-files-folders-or-disks-mchlp1203/mac
