### ISSUE TITLE
Exported HTML file names omit the country TLD for contacts

### ISSUE THREAD

**Issue by JanX2** [ReagentX/imessage-exporter#355]
I have made exports of my messages db using imessage-exporter v2.1.1 on macOS 12.6.5 (Monterey):

`imessage-exporter --format 'html' -c 'compatible' --start-date "$FROM_DATE" --end-date "$TO_DATE" --export-path "$DIR"`

The file names I get omit the country TLD for some contacts: "…@icloud"  instead of "…@icloud.com". 
(Both lower case “C”. Github user iCloud is having fun.)

"…@something.online". seems to work, while "…@something.de" doesn’t.

I checked and the file names are not truncated, because they exceeded MAX_LENGTH.

Can you help or do you want me to try to fix this myself? I’m a software dev, but never touched Rust.

**Comment by ReagentX** [comment]
This only occurs for the last contact in the filename:

https://github.com/ReagentX/imessage-exporter/blob/5b62b61af5178d02b00c1a23702dcbdeb979054c/imessage-exporter/src/exporters/html.rs#L160-L161

It interprets the TLD as the extension, so it gets replaced with `.html`. The contact details inside of the conversation should still be correct.
