### ISSUE TITLE
Unable to export messages from unencrypted iphone backup.

### ISSUE THREAD

**Issue by RayTCosgrove** [ReagentX/imessage-exporter#358]
When attempting to export messages from an unencrypted iphone back up freshly created today, i get the following error:

`Invalid configuration: Database not found at ~/Library/Application Support/MobileSync/Backup/00008120-001610812260201E/3d/3d0d7e5fb2ce288813306e4d4636395e047a3d28`

I checked the 3d/ directory and the file 3d0d7e5fb2ce288813306e4d4636395e047a3d28 is not present in the backup. Perhaps the format of the backups has changed? Is there possibly a simple fix i could use to update which files are looked for in the backup?

Thanks

**Comment by ReagentX** [comment]
The backup format has not changed. Are you sure that the backup was not encrypted with a password? 

What version of iOS/MacOS are you using?
