### ISSUE TITLE
Own messages in RCS group chat have no background color

### ISSUE THREAD

**Issue by jasonfma** [ReagentX/imessage-exporter#361]
RCS group chat messages extract but the html export doesn't set a background color for "me"
example:
<img width="853" alt="Screenshot 2024-11-12 at 14 01 45" src="https://github.com/user-attachments/assets/ce7e8ca9-17be-4a0d-9340-e66e5aacdc5b">

example showing text highlighted:
<img width="863" alt="Screenshot 2024-11-12 at 14 01 58" src="https://github.com/user-attachments/assets/27f7b77e-e3a2-424e-93aa-5d034efb6ae3">

**Comment by jasonfma** [comment]
CSS generated is - `sent Other(" rcs")`
<img width="304" alt="Screenshot 2024-11-12 at 14 08 08" src="https://github.com/user-attachments/assets/597b6401-28c3-4a81-8817-7fa72890078e">

**Comment by jasonfma** [comment]
Guessing we need to add a case for RCS here

https://github.com/ReagentX/imessage-exporter/blob/fa67b1d798291f1dc04cabf5d68d384ba66ee8e1/imessage-database/src/tables/messages/message.rs#L938

I might be able to get to this next week if nobody else has yet.

**Comment by ReagentX** [comment]
What color should we use for RCS?

**Comment by jasonfma** [comment]
On device, RCS shows up the same as SMS for me (i.e. green)

**Comment by ReagentX** [comment]
Thanks!
