### ISSUE TITLE
Review/fix/enhance voice/audio/.caf file play

### ISSUE THREAD

**Issue by ldexterldesign** [ReagentX/imessage-exporter#365]
👋

Hope you're OK!

Thanks for awesome software 😍

Export of voice/audio/.caf files is successful as attachments but the [audio] elems don't seem to play 😕 - I presume you're aware of [this] (although issue is closed and last/latest comment means nothing to me 🤔) but what's the reason and will it get fixed/enhanced soon?

Hope to hear back

Kind thanks

[audio]: https://devdocs.io/html/element/audio
[this]: https://github.com/ReagentX/imessage-exporter/issues/155

**Comment by ReagentX** [comment]
Can you post a screenshot of what your browser displays?

What browser are you using? Most browsers don't support that format: https://en.wikipedia.org/wiki/HTML_audio#Supported_audio_coding_formats

<img width="983" alt="image" src="https://github.com/user-attachments/assets/1f970628-24e2-47e6-9955-351ce797bcd6">
