### ISSUE TITLE
Install issue on OSX Mojave

### ISSUE THREAD

**Issue by john-abrams** [ReagentX/imessage-exporter#376]
What went wrong here when install from x86 installer on old mac with Mojave running was attempted?

iMac:- john$ /Volumes/32GBFAT32/imessage-exporter-x86_64-apple-darwin ; exit;
dyld: cannot load 'imessage-exporter-x86_64-apple-darwin' (load command 0x80000034 is unknown)
Abort trap: 6
logout
Saving session...
...copying shared history...
..saving history... truncating history files...
...completed.
[Process completed]

please advise. thanks.

**Comment by ReagentX** [comment]
This is related to #305. I don't provide prebuilt binaries for 32-bit machines; you will need to compile `imessage-exporter` for your platform.

**Comment by john-abrams** [comment]
got it. thanks.

**Comment by gtoutin** [comment]
I was wondering the same thing. I was able to compile it and export my messages. Here is the binary and some steps I took if you want to compile it yourself. https://github.com/gtoutin/imessage-exporter/releases/tag/v1.0.0
