### ISSUE TITLE
Conversation filter not working;  option error:unexpected argument '-t' found

### ISSUE THREAD

**Issue by zelik888** [ReagentX/imessage-exporter#377]
I can export fine, but I can't filter to export from specific participants.

In the documentation there is a conversation filter argument -t but the macOS binary for apple silicon (and the brew version, which I assume is the same) has the same issue. The help does not show this feature either. 

version: iMessage Exporter 2.1.1
OS: Sonoma 14.6.1
HW: Apple M1 Pro 2021 MB Pro 16
Utilizing default database

**Comment by ReagentX** [comment]
Live Oak has not been released yet: https://github.com/users/ReagentX/projects/17

**Comment by ReagentX** [comment]
Live Oak is now available.
