### ISSUE TITLE
Unable to export: Failed to parse attachment row: incomplete input

### ISSUE THREAD

**Issue by cancel-cloud** [ReagentX/imessage-exporter#391]
Hello together,
i saw the similar issue is already open, but the case you're handeling over there is not helping me here.
Yes, i read [The Readme](https://github.com/ReagentX/imessage-exporter/blob/develop/imessage-exporter/README.md) and took some time tweaking with the arguments, but was't able to figure it out myself.

Thanks in advance for your support!
---

I'm running the exporter through brew, version 2.2.0.
If i run the command
`imessage-exporter -f html -c clone -o ./Downloads/imessage-export/ -t "target@mail.com"`

the output:
`Building cache...
  [1/4] Caching chats...
  [2/4] Caching chatrooms...
  [3/4] Caching participants...
  [4/4] Caching tapbacks...
Cache built!
Filtering for 1 handle across 4 chatrooms...
Unable to export: Failed to parse attachment row: incomplete input`

**imessage-exporter -d**
```
Building cache...
  [1/4] Caching chats...
  [2/4] Caching chatrooms...
  [3/4] Caching participants...
  [4/4] Caching tapbacks...
Cache built!

iMessage Database Diagnostics

Message diagnostic data:
    Total messages: 67064
    Messages not associated with a chat: 2231
Attachment diagnostic data:
    Total attachments: 13080
        Data referenced in table: 14.95 GB
        Data present on disk: 17.65 GB
    Missing files: 539 (4%)
        No path provided: 402
        No file located: 137
Global diagnostic data:
    Total database size: 137.39 MB
    Duplicated contacts: 30

Environment Diagnostics

Detected converters:
    Image converter: sips
    Audio converter: afconvert
    Video converter: ffmpeg
Done!
```
---
what worked was:
`imessage-exporter -f html -o ~/Users/cancelcloud/Downloads/imessage-export/ -t "@"`
that generated the html files in the specific directory.

**Comment by ReagentX** [comment]
Can you check if [this branch](https://github.com/ReagentX/imessage-exporter/tree/feat/cs/fix-negative-total-bytes) ([diff](https://github.com/ReagentX/imessage-exporter/compare/develop..feat/cs/fix-negative-total-bytes)) resolves the crash?

**Comment by cancel-cloud** [comment]
indeed it does work!
now i got a suprising thing:
the messages with my friend are all in the html file, but the date cut off at nov. 21 and between now and then we chatted a lot.
could you explain why that is so?
and the estimated folder size is not correct, the folder i got was 3 nearly 4 GB, that could be beacuse of the errors for the attachments?
Thanks again for checking!
```
Building cache...
  [1/4] Caching chats...
  [2/4] Caching chatrooms...
  [3/4] Caching participants...
  [4/4] Caching tapbacks...
Cache built!
Filtering for 1 handle across 4 chatrooms...
Estimated export size: 14.97 GB
Exporting to /Users/cancelcloud/Downloads/imessage-export/ as html...
⠒ [0s] [###>----------------] 2,178/14,267 (5,920.0123/s, ETA: 2s)                                                                                                                                                         Attachment not found at specified path: "/var/folders/8k/m3dtwcxj6zj1jwwgbh998tlh0000gn/T/com.apple.imagent/TemporaryItems/5B292314-5A98-4A2C-A419-4AD99AEBB5B8/3D47E73B-F88D-4377-9A30-8680523048D4.heic"
Attachment not found at specified path: "/var/folders/8k/m3dtwcxj6zj1jwwgbh998tlh0000gn/T/com.apple.imagent/TemporaryItems/5B292314-5A98-4A2C-A419-4AD99AEBB5B8/3D47E73B-F88D-4377-9A30-8680523048D4.heic"
⠐ [2s] [###################>] 13,761/14,267 (7,103.8279/s, ETA: 0s)                                                                                                                                                        Attachment not found at specified path: "/var/folders/8k/m3dtwcxj6zj1jwwgbh998tlh0000gn/T/com.apple.imagent/TemporaryItems/A09A6BE3-A7BB-47F9-AFC5-53D22DC8ED12/IMG_3856.jpeg"
  [2s] [####################] 14,267/14,267 (6,637.5316/s, ETA: 0s)                                                                                                                                                        Writing HTML footers...
Done!
```

**Comment by ReagentX** [comment]
If you export messages without the `-t` filter, do the messages show up in a different export file? It is possible that the handle association directs some of the messages to a different thread.

RE the estimated export size, see #235.
