### ISSUE TITLE
iMessages sent to someone who's connected via satellite are exported and rendered incorrectly

### ISSUE THREAD

**Issue by nagya** [ReagentX/imessage-exporter#404]
Such messages are exported like this:

```
<div class="sent Other("iMessageLite")">
```

which is not valid HTML, and is rendered as blank (two messages in this screenshot; the date is partially selected to show the text is there, but invisible):

<img width="610" alt="iMessageLite" src="https://github.com/user-attachments/assets/adec0195-6434-4df4-ae22-db9727c92cba" />

Observed in version 2.2.1.

Similar to #361. Ideally the fix wouldn't just special iMessageLite as #363 did for RCS, but also ensure that unknown service IDs are still exported as valid HTML, and they render in some default color, not invisible.

**Comment by ReagentX** [comment]
Thanks for the report; should be a simple fix.
