### ISSUE TITLE
Attachment missing after upgrading to 2.2.1

### ISSUE THREAD

**Issue by nagya** [ReagentX/imessage-exporter#408]
Comparing the output of imessage-exporter 2.1.1 vs 2.2.1, produced from the exact same iOS backup, an attached file is missing in 2.2.1, both from the attachments/ directory, and from the HTML. The message has some text and a photo attached.

The output of `--diagnostics` between the two versions is not different (other than the "Environment Diagnostics" and "Detected converters" sections added in 2.2.1); the total/missing attachment count and other stats are the same.

Diff output:

```
diff -ru 2.1.1 2.2.1
[...]
Only in 2.1.1/attachments/262: 1762.jpeg
[...]
 <div class="message">
 <div class="sent iMessage">
 <p><span class="timestamp">[...]</span>
 <span class="sender">Me</span></p>
 <hr><div class="message_part">
 <span class="bubble">[...]</span>
 </div>
-<hr><div class="message_part">
-<div class="attachment"><img src="attachments/262/1762.jpeg" loading="lazy"></div>
-</div>
 </div>
 </div>
```

**Comment by ReagentX** [comment]
Without seeing the backups themselves I can't really debug this. If you have more actionable information I will reopen.
