### ISSUE TITLE
Feature: Export from date

### ISSUE THREAD

**Issue by NoLooseEnds** [ReagentX/imessage-exporter#48]
Feature request. Export from date. Could make it easier to automate backups, just need exact days, etc.

**Comment by ReagentX** [comment]
This is a good feature, sometimes exports get really long (I have some going back go 2011).  Automatically splitting up exports by date and setting an arbitrary start date are both good feature ideas.

**Comment by AntlerDM** [comment]
I like this idea as well. Especially if you can specify a date range, so very large conversations can be a bit more manageable.
