### ISSUE TITLE
Doesn't seem to be in crates.io

### ISSUE THREAD

**Issue by jtippett** [ReagentX/imessage-exporter#52]
Running ```cargo install imessage_exporter``` I received this error:

```    
Updating crates.io index
error: could not find `imessage_exporter` in registry `crates-io` with version `*` 
```

Anything special I need to do?

**Comment by ReagentX** [comment]
https://crates.io/crates/imessage-exporter

It's a typo, I wrote an `_` in the docs when it should be a `-`.

**Comment by ReagentX** [comment]
I will cut a release to update the crates.io pages when I have code changes to push.
