### ISSUE TITLE
`transfer_name` column not present in Attachments table

### ISSUE THREAD

**Issue by themorgantown** [ReagentX/imessage-exporter#54]
Thanks for making this. I wish I could give you a slice of 🍰 

After running: 

```
imessage-exporter -f html
Building cache...
[1/4] Caching chats...
[2/4] Caching chatrooms...
[3/4] Caching participants...
[4/4] Caching reactions...
Cache built!
Exporting to /Users/myusername/imessage_export as html...
```
I get this error: 

`Unable to launch: Failed to parse row: Invalid column type Null at index: 12, name: transfer_name` 

Any other debugging info I can share?

**Comment by ReagentX** [comment]
Seems like your iMessage database doesn't have the `transfer_name` column in the `attachments` table. That data is required currently:

https://github.com/ReagentX/imessage-exporter/blob/8bc5c9a0166fb01f8738d504268406174c1de15c/imessage-database/src/tables/attachment.rs#L38

https://github.com/ReagentX/imessage-exporter/blob/8bc5c9a0166fb01f8738d504268406174c1de15c/imessage-database/src/tables/attachment.rs#L51

To fix that, I need to either set a default for that column or make it optional. 

How old is this database? All of mine going back to 2011 have this column.

**Comment by themorgantown** [comment]
> How old is this database? All of mine going back to 2011 have this column. 

I see messages going back to Sept 2015

**Comment by ReagentX** [comment]
Is this `chat.db` file from an iOS device or a macOS one?

**Comment by themorgantown** [comment]
macOS

**Comment by themorgantown** [comment]
confirmed fix! Thanks 🍰 🍰
