### ISSUE TITLE
Lack of compatibility with old iMessage chat db's?

### ISSUE THREAD

**Issue by charlesalec** [ReagentX/imessage-exporter#69]
I have a chat.db as well as the attachment folder backed up to a drive, I put it on my desktop, and ran the command as follows:
`imessage-exporter --db-path "/path/to/chat_folder/" -f html`
And I get the full disk access error -- I tried specifying chat.db at the end of the path too (as I'm not sure if that is appended, or whether the .db file needs to be specified.

Great project though! I've been backing up my iMessage chat db's for years, and have been wanting to make this kind of program for years.

**Comment by ReagentX** [comment]
This software should be compatible with older tables; I was able to export from a backup made in 2011.

You should specify the filename when using a custom path, ex:

```zsh
% imessage-exporter -f html --no-copy -p /Volumes/external/chat.db
```

If that does not work, ensure the path you provide is correct and accessible from your terminal emulator (I generally try `open /Volumes/external/chat.db` for diagnosing path issues).

**Comment by charlesalec** [comment]
Hi, thanks for the reply!
Here's the error I get with the command you mentioned about opening from a custom path:
`Building cache...
[1/4] Caching chats...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SqliteFailure(Error { code: CannotOpen, extended_code: 14 }, Some("unable to open database file"))', /Users/charlesdowns/.cargo/registry/src/github.com-1ecc6299db9ec823/imessage-database-1.0.0/src/tables/chat.rs:34:54
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace`

**Comment by ReagentX** [comment]
I think this is a dupe of #74 (well, technically that issue is a dupe of this one!), which will be fixed in the Mountain Sage release.

**Comment by charlesalec** [comment]
That did actually solve it - you're a genius! thanks!

**Comment by ReagentX** [comment]
Cheers!
