### ISSUE TITLE
FAQ needed?

### ISSUE THREAD

**Issue by paul-hammant** [ReagentX/imessage-exporter#71]
For example:

Q: Does `imessage-exporter` export message conversations that are on a user's iPhone but **not** mirrored on the user's otherwise in-sync Mac?
A: No, the user will have to ensure that iPhone conversations are each mirrored onto their Mac before they attempt export 

Q: Can you run expert again and again? How does the exporter handle previously exported messages
A: `imessage-exporter`  merges in missing messages for each conversation.

Q: If an export is done. then message(s) are deleted through Apple's messages apps, does a subsequent export delete the same messages from the export file set?
A: No, the exporter does not replicate deletes onto a previous exported set of files

**Comment by ReagentX** [comment]
Yeah, this is a good idea. Between your suggestions and the two Reddit threads I have a lot of questions to add.
