### ISSUE TITLE
[BUG] video type video/quicktime breaks compatibility with Chromium based browsers

### ISSUE THREAD

**Issue by mbaran5** [ReagentX/imessage-exporter#73]
A video with the src set to 

`<video controls> <source src="attachments/71cba48a-707b-4dee-b494-ba43ef5c0f0c.mov" type="video/quicktime"> </video>` will not play in Edge or Chrome.

![image](https://user-images.githubusercontent.com/583865/213037233-0b5bdc57-c110-49b8-b46b-d9902b61ab9b.png)

A video with the src set to 

`<video controls> <source src="attachments/71cba48a-707b-4dee-b494-ba43ef5c0f0c.mov" </video>` play just fine. 

From a quick google, this seems to have been or is an issue https://secure.phabricator.com/T13135

**Comment by ReagentX** [comment]
That's pesky. Right now that `mime_type` is parsed from the table. Need to have better logic to handle cases like this.

https://github.com/ReagentX/imessage-exporter/blob/a825a2e9dd96c7148877d4c8c8c347f2dba292c7/imessage-database/src/tables/attachment.rs#L165-L184

**Comment by mbaran5** [comment]
I can also confirm this workaround works as well

https://github.com/nextcloud/files_videoplayer/issues/129#issuecomment-487596247

I've tested this in a conversation of mine.

**Comment by ReagentX** [comment]
Really helpful, thank you for the report and the workarounds!

**Comment by mbaran5** [comment]
No problemo! This finally lets me get something like 120GB of message content off my phone/iCloud and I can turn on discard after 1 year and still keep my history.
