### ISSUE TITLE
'Unable to open database file' error when specifying the database path option

### ISSUE THREAD

**Issue by JoeNyland** [ReagentX/imessage-exporter#74]
I'm getting the following error when specifying the database path option:

```
$ RUST_BACKTRACE=full ./imessage-exporter-aarch64-apple-darwin -o /tmp/imessage/out/ -f html -p /tmp/imessage/chat.db 
Building cache...
[1/4] Caching chats...
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: SqliteFailure(Error { code: CannotOpen, extended_code: 14 }, Some("unable to open database file"))', /Users/chris/.cargo/registry/src/github.com-1ecc6299db9ec823/imessage-database-1.0.0/src/tables/chat.rs:34:54
stack backtrace:
   0:        0x10415cdf8 - __mh_execute_header
   1:        0x1040c184c - __mh_execute_header
   2:        0x10413c988 - __mh_execute_header
   3:        0x1041600b0 - __mh_execute_header
   4:        0x10415fd10 - __mh_execute_header
   5:        0x104160be0 - __mh_execute_header
   6:        0x104160768 - __mh_execute_header
   7:        0x1041606dc - __mh_execute_header
   8:        0x1041606b8 - __mh_execute_header
   9:        0x1041725c8 - __mh_execute_header
  10:        0x104172798 - __mh_execute_header
  11:        0x1040f7bcc - __mh_execute_header
  12:        0x1040ea5e0 - __mh_execute_header
  13:        0x1040f217c - __mh_execute_header
  14:        0x1040e8560 - __mh_execute_header
Abort trap: 6
```

I can't see any more information on _why_ the file couldn't be opened; as far as I can see there's nothing in the permissions leading up to and including the file that would deny access:

```
$ stat /tmp
  File: /tmp -> private/tmp
  Size: 11        	Blocks: 0          IO Block: 4096   symbolic link
Device: 1,16	Inode: 1152921500312421341  Links: 1
Access: (0755/lrwxr-xr-x)  Uid: (    0/    root)   Gid: (    0/   wheel)
...
$ stat /private/tmp
  File: /private/tmp
  Size: 384       	Blocks: 0          IO Block: 4096   directory
Device: 1,16	Inode: 110015026   Links: 12
Access: (1777/drwxrwxrwt)  Uid: (    0/    root)   Gid: (    0/   wheel)
...
$ stat /tmp/imessage
  File: /tmp/imessage
  Size: 224       	Blocks: 0          IO Block: 4096   directory
Device: 1,16	Inode: 110861970   Links: 7
Access: (0755/drwxr-xr-x)  Uid: (  501/joenyland)   Gid: (   20/   staff)
...
$ stat /tmp/imessage/chat.db 
  File: /tmp/imessage/chat.db
  Size: 16932864  	Blocks: 33072      IO Block: 4096   regular file
Device: 1,16	Inode: 110862025   Links: 1
Access: (0644/-rw-r--r--)  Uid: (  501/joenyland)   Gid: (   20/   staff)
...
```

I also get the same behaviour if I run this inside my home directory. I'm doing this in `/tmp` just to keep things separate and also in an attempt to reduce the chances of access being denied through some sort of permissions.

If I run the tool without specifying a different DB, it works fine (therefore using `~/Library/Messages/chat.db`). It's just that I want to export from a backed up chat.db file.

I've got two backed up chat.db files from differing macOS versions that give the same error. One from macOS 13.1 and the other from 11.7.2.

**Comment by ReagentX** [comment]
Detail on extended error code 14: https://www.sqlite.org/rescode.html#cantopen

I get this occasionally when testing with databases on external drives, sadly I am not sure what causes it. Usually opening up the tables in a separate program will make it work again; sometimes it takes a few tries. I need to investigate this more but I can't dependably recreate it.

***

Semi-related, the error message will look a lot cleaner in the upcoming Mountain Sage release.

**Comment by JoeNyland** [comment]
> Usually opening up the tables in a separate program will make it work again

Interesting! I tried opening the DB file with `sqlite` and then retried `imessage-exporter` and still got the same error.

Then I tried `sqlite` again and ran `.table` to list the tables (just making sure the file wasn't corrupt or something) and then retried `imessage-exporter` and it suddenly started working!

I noticed that after running `.tables` in `sqlite` the `*-shm` and `*wal` files were created alongside the DB file but the DB file itself wasn't modified. So I wonder if the absence of the `*-shm` and `*wal` files is something to do with the issue 🤔 

I'd say my issue here is resolved -- in that I can now use the tool with my backup DB files -- but I guess it would be better UX if the `imessage-exporter` were to handle the absence of these files better. That's up to you if you want it to do something like that, though. Do you want me to leave this issue open for that, or would you prefer me to open a new one that's more specifically about handling the absence of those files?

**Comment by ReagentX** [comment]
Thank you for posting your troubleshooting steps, that is very helpful information. Let's leave this open to track the problem; I consider this behavior to be a little buggy.

Details on those files: https://www.sqlite.org/walformat.html

**Comment by ReagentX** [comment]
This is a SQLite issue:

- https://github.com/poliorcetics/sqlite-macos-repro
- https://github.com/rusqlite/rusqlite/issues/1206

Mountain Sage will bundle a version of `lsqlite3` for #66, and a side effect of that is resolving this issue as well.
