### ISSUE TITLE
FAQ deleted messages item needs wordsmithing, IMO

### ISSUE THREAD

**Issue by paul-hammant** [ReagentX/imessage-exporter#76]
> Q: Are deleted messages simply erased from the database? A: Yes, this tool cannot recover deleted messages.

delete messages where? .. erased from where? Differentiation between canonical Apple DB (Sqlite - multiple locations) and the `imessage-exporter` quasi database needed.

**Comment by ReagentX** [comment]
I don't follow, but I am happy to make changes.
