### ISSUE TITLE
Add updating feature

### ISSUE THREAD

**Issue by danielrezaie** [ReagentX/imessage-exporter#80]
it would be amazing if you could add a feature where the software can update the last export to include new messages, as right now when the software is ran a second time in the same directory, the file has 2 copies of the text inside.
thanks

**Comment by ReagentX** [comment]
Closed in #96.

**Comment by lhunath** [comment]
Can I ask how #96 resolves this ticket? There is no updating functionality available; `imessage-exporter` just refuses to export again (avoiding the duplication), but leaving entirely unaddressed the original need that gave rise to the issue: ie. once an export is made, the export becomes effectively read-only and exporting becomes impossible until the export is deleted.

Sure, we can manually delete the previous export, but what if messages are lost in the source? Ideally, the update should not involve a loss of already-exported messages.
