### ISSUE TITLE
Feature request: turn off lazy loading option

### ISSUE THREAD

**Issue by illustrious-otter** [ReagentX/imessage-exporter#86]
Hi, I love this tool - many thanks!

I am using this to generate pdf versions of message threads and didn't have any luck with wkhtml but found with some extra CSS I can get a very good result printing to pdf from Safari - however, in longer threads, many images get skipped unless I remove loading="lazy" so it would be nice to have a --no-lazy switch.

**Comment by ReagentX** [comment]
This is a great suggestion.
